var events = require('events') 
var emitter = new events.EventEmitter()
emitter.on('knock', function() {  console.log('Who\'s there?') })
emitter.on('knock', function() {  console.log('Go away!') })
console.log('knock')
emitter.emit('knock')
